# Generated by Django 3.0.3 on 2020-04-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200414_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_movie_link', to='movie.Movie'),
        ),
    ]
