# Generated by Django 3.0.3 on 2020-04-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20200416_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='movie.Movie'),
        ),
    ]
