# Generated by Django 3.0.3 on 2020-04-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20200418_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='veiws_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='movie.Movie'),
        ),
    ]
